"""autogenerated by genmsg_py from MotorControllerStatusStamped.msg. Do not edit."""
import roslib.message
import struct

import motor.msg
import std_msgs.msg

class MotorControllerStatusStamped(roslib.message.Message):
  _md5sum = "4a4d90dbcf4616003109b40003e27174"
  _type = "motor/MotorControllerStatusStamped"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header                 header  # Timestamp, sequence number, and frame id

MotorControllerStatus  status  # Motor Controller Status information

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: motor/MotorControllerStatus
# This is the msg definition for the AX3500 motor controller status struct

Header  header                   # Timestamp, sequence number, and frame id

# Wheel information
float32 left_wheel_displacement  # m
float32 right_wheel_displacement # m
float32 left_wheel_velocity      # m/s
float32 right_wheel_velocity     # m/s

# AX3500 information
#float32 left_motor_current       # amps
#float32 right_motor_current      # amps
int32   temperature              # degrees Celsius
float32 motor_battery            # volts
float32 controller_battery       # volts

#bool    motors_enabled           # Enabled (true) or E-Stopped (false)

"""
  __slots__ = ['header','status']
  _slot_types = ['Header','motor/MotorControllerStatus']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       header,status
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(MotorControllerStatusStamped, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      if self.status is None:
        self.status = motor.msg.MotorControllerStatus()
    else:
      self.header = std_msgs.msg._Header.Header()
      self.status = motor.msg.MotorControllerStatus()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.status.header.seq, _x.status.header.stamp.secs, _x.status.header.stamp.nsecs))
      _x = self.status.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_4fi2f.pack(_x.status.left_wheel_displacement, _x.status.right_wheel_displacement, _x.status.left_wheel_velocity, _x.status.right_wheel_velocity, _x.status.temperature, _x.status.motor_battery, _x.status.controller_battery))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      if self.status is None:
        self.status = motor.msg.MotorControllerStatus()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.status.header.seq, _x.status.header.stamp.secs, _x.status.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.status.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.status.left_wheel_displacement, _x.status.right_wheel_displacement, _x.status.left_wheel_velocity, _x.status.right_wheel_velocity, _x.status.temperature, _x.status.motor_battery, _x.status.controller_battery,) = _struct_4fi2f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.status.header.seq, _x.status.header.stamp.secs, _x.status.header.stamp.nsecs))
      _x = self.status.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_4fi2f.pack(_x.status.left_wheel_displacement, _x.status.right_wheel_displacement, _x.status.left_wheel_velocity, _x.status.right_wheel_velocity, _x.status.temperature, _x.status.motor_battery, _x.status.controller_battery))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      if self.status is None:
        self.status = motor.msg.MotorControllerStatus()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.status.header.seq, _x.status.header.stamp.secs, _x.status.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.status.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.status.left_wheel_displacement, _x.status.right_wheel_displacement, _x.status.left_wheel_velocity, _x.status.right_wheel_velocity, _x.status.temperature, _x.status.motor_battery, _x.status.controller_battery,) = _struct_4fi2f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_3I = struct.Struct("<3I")
_struct_4fi2f = struct.Struct("<4fi2f")
